language: ruby
script: bundle exec rake
sudo: false
cache: bundler
rvm:
  - '2.3.0'
  - '2.2'
  - '2.1'
  - '2.0'

gemfile:
  - Gemfile

notifications:
  email: false

addons:
  code_climate:
    repo_token:
      secure: "MJuQnvBt4+7QucNh3YWIur3AcDMsIEaIaEkT+tWbE/153lLdyNWP78hBZFN5Ktbq156O05cop6jeXxL8skHJsBaCedx1Qp/agDwO4CX4Ia7pQh9WN4ouYGFkFvrEc4h0hDbo8fgO0lZcZg6PCTMItBXJxqF3URH+zzfvGDOOi9w="
